# Site settings
title: Reunion
header-img: img/home-bg.png
email: haoleboy3000@yahoo.com
copyright_name: TropintheBard
description: > # this means to ignore newlines until "baseurl:"
  Restarting My Coding Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  TropintheBard
learn_profile: TropintheBard
email_username: haoleboy3000@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
